---
- name: Absent docker
  when:
    - metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy] is defined
  block:
    - name: "Stop container of {{ exporter.name }}"
      become: true
      ignore_errors: true
      community.docker.docker_container:
        name: "{{ exporter.name }}"
        state: stopped

    - name: "Remove container of {{ exporter.name }}"
      become: true
      ignore_errors: true
      community.docker.docker_container:
        name: "{{ exporter.name }}"
        state: absent

    - name: "Remove cfg files for {{ exporter.name }}"
      become: true
      when:
        - exporter.cfg_files is defined
        - exporter.cfg_files is iterable
        - exporter.cfg_files | length > 0
      loop: "{{ exporter.cfg_files }}"
      loop_control:
        loop_var: file
        label: "file: {{ file.dest }}"
      ansible.builtin.file:
        path: "{{ file.dest }}"
        state: absent

