---

- name: Absent binary
  when:
    - metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy] is defined
  block:
    - name: "Stop {{ exporter.name }}"
      become: true
      ignore_errors: true
      ansible.builtin.service:
        name: "{{ exporter.name }}"
        state: stopped
        enabled: false


    - name: "Delete systemd unit file for {{ exporter.name }}"
      when:
        - ansible_service_mgr == "systemd"
      block:
        - name: "Delete systemd unit file for {{ exporter.name }}"
          become: true
          ansible.builtin.file:
            path: /etc/systemd/system/{{ exporter.name }}.service
            state: absent

        - name: Systemd daemon-reload
          become: true
          ansible.builtin.systemd:
            daemon_reload: true


    - name: "Delete sysvinit file for {{ exporter.name }}"
      when:
        - ansible_service_mgr == "sysvinit"
      block:
        - name: "Disable sysvinit file for {{ exporter.name }}"
          become: true
          ansible.builtin.command:
            cmd: "chkconfig {{ exporter.name }} off"

        - name: "Create sysvinit file for {{ exporter.name }}"
          become: true
          ansible.builtin.file:
            path: /etc/init.d/{{ exporter.name }}
            state: absent


    - name: "Delete user for {{ exporter.name }}"
      become: true
      when:
        - metrics_exporters_specs[exporter.name].run_user_name != "root"
      ansible.builtin.user:
        name: "{{ metrics_exporters_specs[exporter.name].run_user_name }}"
        state: absent


    # - name: "Remove binary of {{ exporter.name }}"
    #   become: true
    #   ansible.builtin.file:
    #     path: >-
    #       {{- metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy].install_bin_path -}}
    #       /{{- metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy].install_bin_name -}}
    #     state: absent


    - name: "Remove binary files for {{ exporter.name }}"
      become: true
      when:
        - metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy].bin_files is defined
        - metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy].bin_files is iterable
        - metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy].bin_files | length > 0
      loop: "{{ metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy].bin_files }}"
      loop_control:
        loop_var: file
        label: "file: {{ file.src }}"
      ansible.builtin.file:
        path: "{{ exporter.install_path }}/{{ file.dest }}"
        state: absent


    - name: "Remove cfg files for {{ exporter.name }}"
      become: true
      when:
        - exporter.cfg_files is defined
        - exporter.cfg_files is iterable
        - exporter.cfg_files | length > 0
      loop: "{{ exporter.cfg_files }}"
      loop_control:
        loop_var: file
        label: "file: {{ file.dest }}"
      ansible.builtin.file:
        path: "{{ file.dest }}"
        state: absent
