---

- name: Present docker
  when:
    - metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy] is defined
  block:
    - name: "Deploy cfg files for {{ exporter.name }}"
      become: true
      when:
        - exporter.cfg_files is defined
        - exporter.cfg_files is iterable
        - exporter.cfg_files | length > 0
      loop: "{{ exporter.cfg_files }}"
      loop_control:
        loop_var: file
        label: "file: {{ file.dest }}"
      ansible.builtin.copy:
        content: "{{ file.content | default(omit) }}"
        src: "{{ file.src | default(omit) }}"
        dest: "{{ file.dest }}"
        mode: "{{ file.mode }}"
        owner: "{{ file.owner }}"
        group: "{{ file.group }}"
        # state: present


    # - name: "Stop container of {{ exporter.name }}"
    #   become: true
    #   ignore_errors: true
    #   community.docker.docker_container:
    #     name: "{{ exporter.name }}"
    #     state: stopped


    # - name: "Remove container of {{ exporter.name }}"
    #   become: true
    #   ignore_errors: true
    #   community.docker.docker_container:
    #     name: "{{ exporter.name }}"
    #     state: absent


    - name: "Start container of {{ exporter.name }}"
      become: true
      community.docker.docker_container:
        name: "{{ exporter.name }}"
        state: started
        image: "{{ metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy]['images'][exporter.platform].docker_image }}:{{ exporter.version }}"
        detach: true
        recreate: true
        restart: true
        # privileged: true
        # user: root
        user: "{{ metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy][exporter.platform]['images'].user | default(omit) }}"
        privileged: "{{ metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy][exporter.platform]['images'].privileged | default(false) }}"
        pid_mode: "{{ metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy][exporter.platform]['images'].pid_mode | default(omit) }}"
        network_mode: "{{ metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy][exporter.platform]['images'].network_mode | default(omit) }}"
        restart_policy: "{{ metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy][exporter.platform]['images'].restart_policy | default('unless-stopped') }}"
        command: >-
          {{ exporter.options | join(" ") }}
        env:
          TZ: Europe/Paris
        volumes: "{{ exporter.docker_volumes | default(omit) }}"
        published_ports: "{{ exporter.docker_published_ports | default(omit) }}"
        # memory: 128m
        # cpus: !!float "0.15"
        cpus: "{{ metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy][exporter.platform]['images'].cpus | default('0.15') }}"
        memory: "{{ metrics_exporters_specs[exporter.name]['deploy'][exporter.deploy][exporter.platform]['images'].memory | default('128m') }}"
